<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J0SOEVV" failures="1" tests="8" name="Test" time="0.116" errors="0" timestamp="2020-06-05T00:05:03 IST">
  <testcase classname="Package1.DataProvideer" name="Test1" time="0.01"/>
  <testcase classname="Package1.DataProvideer" name="Test1" time="0.002"/>
  <testcase classname="Package1.DataProvideer" name="Test2" time="0.004"/>
  <testcase classname="Package1.DataProvideer" name="Test2" time="0.002"/>
  <testcase classname="Package1.AssertEx" name="Test1" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [Hai world] but found [Hello World]">
      <![CDATA[java.lang.AssertionError: expected [Hai world] but found [Hello World]
at Package1.AssertEx.Test1(AssertEx.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="Package1.TestNGClass" name="Test3" time="0.002"/>
  <testcase classname="Package1.TestNGClass" name="Test2" time="0.002"/>
  <testcase classname="Package1.TestNGClass" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Test -->
