<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="6" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-06-05T00:05:03 IST" name="Suite" finished-at="2020-06-05T00:05:03 IST" duration-ms="116">
    <groups>
    </groups>
    <test started-at="2020-06-05T00:05:03 IST" name="Test" finished-at="2020-06-05T00:05:03 IST" duration-ms="116">
      <class name="Package1.DataProvideer">
        <test-method signature="Test1(java.lang.String, java.lang.String, int)[pri:0, instance:Package1.DataProvideer@1df82230]" started-at="2020-06-05T00:05:03 IST" name="Test1" data-provider="get" finished-at="2020-06-05T00:05:03 IST" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dhanabal]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[17111985]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[34]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method signature="Test1(java.lang.String, java.lang.String, int)[pri:0, instance:Package1.DataProvideer@1df82230]" started-at="2020-06-05T00:05:03 IST" name="Test1" data-provider="get" finished-at="2020-06-05T00:05:03 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Susai]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[17111984]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[36]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method signature="Test2(java.lang.String, java.lang.String, int)[pri:0, instance:Package1.DataProvideer@1df82230]" started-at="2020-06-05T00:05:03 IST" name="Test2" data-provider="get" finished-at="2020-06-05T00:05:03 IST" duration-ms="4" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dhanabal]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[17111985]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[34]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method signature="Test2(java.lang.String, java.lang.String, int)[pri:0, instance:Package1.DataProvideer@1df82230]" started-at="2020-06-05T00:05:03 IST" name="Test2" data-provider="get" finished-at="2020-06-05T00:05:03 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Susai]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[17111984]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[36]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
      </class> <!-- Package1.DataProvideer -->
      <class name="Package1.AssertEx">
        <test-method signature="Test1()[pri:0, instance:Package1.AssertEx@22635ba0]" started-at="2020-06-05T00:05:03 IST" name="Test1" finished-at="2020-06-05T00:05:03 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hai world] but found [Hello World]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hai world] but found [Hello World]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Package1.AssertEx.Test1(AssertEx.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
      </class> <!-- Package1.AssertEx -->
      <class name="Package1.TestNGClass">
        <test-method signature="Test3()[pri:3, instance:Package1.TestNGClass@13c10b87]" started-at="2020-06-05T00:05:03 IST" name="Test3" finished-at="2020-06-05T00:05:03 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method signature="Test2()[pri:2, instance:Package1.TestNGClass@13c10b87]" started-at="2020-06-05T00:05:03 IST" name="Test2" finished-at="2020-06-05T00:05:03 IST" depends-on-methods="Package1.TestNGClass.Test3" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method signature="Test1()[pri:1, instance:Package1.TestNGClass@13c10b87]" started-at="2020-06-05T00:05:03 IST" name="Test1" finished-at="2020-06-05T00:05:03 IST" depends-on-methods="Package1.TestNGClass.Test2" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test
at Package1.TestNGClass.Test1(TestNGClass.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
      </class> <!-- Package1.TestNGClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
